version: '3.8'

services:
  whisper-node:
    build: .
    container_name: whisper-node
    volumes:
      - whisper_uploads:/app/uploads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper.rule=Host(`whisper1.amrotak.nl`)"
      - "traefik.http.routers.whisper.entrypoints=websecure"
      - "traefik.http.routers.whisper.tls.certresolver=myresolver"
      - "traefik.http.services.whisper.loadbalancer.server.port=5000"
    networks:
      - traefik

volumes:
  whisper_uploads:

networks:
  traefik:
    external: true
